# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enkryptify < Formula
  desc "Official Enkryptify CLI for injecting secrets into your codebase"
  homepage "https://enkryptify.com"
  version "0.1.1"
  license "GPL-3.0-only"

  on_macos do
    on_intel do
      url "https://github.com/Enkryptify/cli/releases/download/v0.1.1/enkryptify_Darwin_x86_64.tar.gz"
      sha256 "5dd39bf4d9f394e1d7b152af2b0dd1355ab1160f2fb259e4b551e878844bb04e"

      def install
        bin.install "enkryptify"
      end
    end
    on_arm do
      url "https://github.com/Enkryptify/cli/releases/download/v0.1.1/enkryptify_Darwin_arm64.tar.gz"
      sha256 "202bb562a702aa4aadeda3001df5ace1a3918f326468ba85f506379fed7b20f9"

      def install
        bin.install "enkryptify"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Enkryptify/cli/releases/download/v0.1.1/enkryptify_Linux_x86_64.tar.gz"
        sha256 "43d1704ab166a6610d781ba2a84990a3caf92ce7904e47f586cc1fbbaaecbabc"

        def install
          bin.install "enkryptify"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Enkryptify/cli/releases/download/v0.1.1/enkryptify_Linux_armv6.tar.gz"
        sha256 "72c80fce791a0b0b7307ff463eaa8c0333ea06a7ef810eddc08c0ee2bec0e09e"

        def install
          bin.install "enkryptify"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Enkryptify/cli/releases/download/v0.1.1/enkryptify_Linux_arm64.tar.gz"
        sha256 "4f94325d62a7b2db10711fab4f74515822de060baab50e6130514c8d2aa1c3ef"

        def install
          bin.install "enkryptify"
        end
      end
    end
  end

  test do
    system "#{bin}/enkryptify --version"
  end
end
