# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enkryptify < Formula
  desc "Official Enkryptify CLI for injecting secrets into your codebase"
  homepage "https://enkryptify.com"
  version "0.1.10"
  license "GPL-3.0-only"

  on_macos do
    on_intel do
      url "https://github.com/Enkryptify/cli/releases/download/v0.1.10/enkryptify_Darwin_x86_64.tar.gz"
      sha256 "e6e55d59dcc5697b573ec1b4c429cedffb8f9791ad755101f2c373a2cf71262a"

      def install
        bin.install "ek"
      end
    end
    on_arm do
      url "https://github.com/Enkryptify/cli/releases/download/v0.1.10/enkryptify_Darwin_arm64.tar.gz"
      sha256 "465bc9b6612fae1f1c462a10ed731f8a58f3c7a8252d351883fc28646040e9ee"

      def install
        bin.install "ek"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Enkryptify/cli/releases/download/v0.1.10/enkryptify_Linux_x86_64.tar.gz"
        sha256 "e32e8f5340862ab27bc8c94bb4319299c58d71f1fb70716b7c3b3aa862cb35fe"

        def install
          bin.install "ek"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Enkryptify/cli/releases/download/v0.1.10/enkryptify_Linux_armv6.tar.gz"
        sha256 "fb8e6b6af0ae99c120319626ab9fdc1ca2234cd6000051ecb280401c3b5110af"

        def install
          bin.install "ek"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Enkryptify/cli/releases/download/v0.1.10/enkryptify_Linux_arm64.tar.gz"
        sha256 "80ca383b8580739c625846c92b52b9a3d3228fc31c7c5bc7e24b78f54d84b7f0"

        def install
          bin.install "ek"
        end
      end
    end
  end

  test do
    system "#{bin}/ek --version"
  end
end
